// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lsp.model;

import com.lsp.model.Driver;

privileged aspect Driver_Roo_JavaBean {
    
    public String Driver.getLicence() {
        return this.licence;
    }
    
    public void Driver.setLicence(String licence) {
        this.licence = licence;
    }
    
}
